version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
  ignore:
    - dependency-name: "django"
      versions: [">=5.1.0"]
    - dependency-name: "ruff"
  groups:
    django-dependencies:
      dependency-type: "production"
      patterns:
        - "Django"
        - "django*"
        - "asgiref"
        - "sqlparse"
        - "python-dateutil"
        - "six"
        - "pytz"
    pre-commit-dependencies:
      dependency-type: "development"
      patterns:
        - "pre-commit"
        - "cfgv"
        - "identify"
        - "nodeenv"
        - "setuptools"
        - "PyYAML"
        - "virtualenv"
        - "distlib"
        - "filelock"
        - "platformdirs"
    pytest-django-dependencies:
      dependency-type: "development"
      patterns:
        - "pytest-django"
        - "pytest"
        - "iniconfig"
        - "packaging"
        - "pluggy"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
