version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
  ignore:
    - dependency-name: "django"
      versions: [">=5.1.0"]
    - dependency-name: "ruff"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
